name: Feature
description: New feature request
title: "feat: "
labels:
  - type:feature
body:
  - type: markdown
    attributes:
      value: |
        Заполните поля ниже.
  - type: textarea
    id: story
    attributes:
      label: User story
      description: "Как <роль>, я хочу <что>, чтобы <зачем>"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      value: |
        - [ ] ...
    validations:
      required: true
